# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: rabits/qt

    steps:
      - checkout
      - run: cd COMP3004-TEAM25
      - run: qmake -makefile && make
