# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - run: source /opt/qt55/bin/qt55-env.sh
      - run: /opt/qt54/bin/qmake -makefile && make

  test:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - run: /opt/qt54/bin/qmake -makefile && make check
