# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    working_directory: ~/

    steps:
      - run: qmake -makefile && make

  test:
    docker:
      - image: buildpack-deps:trusty

    working_directory: ~/

    steps:
      - run: qmake -makefile && make check
