# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: rabits/qt:5.13-desktop

    steps:
      - checkout
      - run: qmake -makefile
      - run: make

  test:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - run: sudo apt-get update -y; true
      - run: sudo apt-get install apt -y
      - run: sudo add-apt-repository ppa:beineri/opt-qt542 -y
      - run: sudo apt-get update -y; true
      - run: sudo apt-get install -y qt54webkit libwebkit-dev libgstreamer0.10-dev
      - run: echo "/opt/qt54/bin/qt54-env.sh" >> ~/.circlerc
      - checkout
      - run: qmake Team25.pro
      - run: make qmake_all
      - run: QT_DEBUG_PLUGINS=1 make check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
