# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: rabits/qt:5.13-desktop

    steps:
      - checkout
      - run: qmake -makefile
      - run: make

  test:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - run: sudo apt-get -y install qt5-default qt5-qmake qtbase5-dev libqt5webkit5-dev
      - run: sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
      - run: sudo apt-get update
      - run: sudo apt-get install qt55base qt55webkit
      - run: echo 'source /opt/qt55/bin/qt55-env.sh' >> ${CIRCLECI_HOME}/.circlerc
      - checkout
      - run: qmake Team25.pro
      - run: make qmake_all
      - run: QT_DEBUG_PLUGINS=1 make check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
